In [1]:
# # Installation Numpy:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = arr[0:9:2]
arr2

array([0, 2, 4, 6, 8])

In [6]:
arr2[0] = 10
arr2

array([10,  2,  4,  6,  8])

In [7]:
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
val = np.nan
val

nan

In [12]:
!pip install pandas

In [13]:
import pandas as pd
url = 'https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert'
df = pd.read_csv(url)
df.head()

INSEE commune                  Commune  Agriculture  Autres transports  \
0         01001  L'ABERGEMENT-CLEMENCIAT  3711.425991                NaN   
1         01002    L'ABERGEMENT-DE-VAREY   475.330205                NaN   
2         01004        AMBERIEU-EN-BUGEY   499.043526         212.577908   
3         01005      AMBERIEUX-EN-DOMBES  1859.160954                NaN   
4         01006                  AMBLEON   448.966808                NaN   

   Autres transports international  CO2 biomasse hors-total      Déchets  \
0                              NaN               432.751835   101.430476   
1                              NaN               140.741660   140.675439   
2                              NaN             10313.446515  5314.314445   
3                              NaN              1144.429311   216.217508   
4                              NaN                77.033834    48.401549   

      Energie  Industrie hors-énergie   Résidentiel       Routier  \
0    2.354558                6.911213    309.358195    793.156501   
1    2.354558                6.911213    104.866444    348.997893   
2  998.332482             2930.354461  16616.822534  15642.420313   
3   94.182310              276.448534    663.683146   1756.341319   
4         NaN                     NaN     43.714019    398.786800   

      Tertiaire  
0    367.036172  
1    112.934207  
2  10732.376934  
3    782.404357  
4     51.681756

In [19]:
df.set_index('INSEE commune', inplace=True, drop=True)
df.head()

Commune  Agriculture  Autres transports  \
INSEE commune                                                            
01001          L'ABERGEMENT-CLEMENCIAT  3711.425991                NaN   
01002            L'ABERGEMENT-DE-VAREY   475.330205                NaN   
01004                AMBERIEU-EN-BUGEY   499.043526         212.577908   
01005              AMBERIEUX-EN-DOMBES  1859.160954                NaN   
01006                          AMBLEON   448.966808                NaN   

               Autres transports international  CO2 biomasse hors-total  \
INSEE commune                                                             
01001                                      NaN               432.751835   
01002                                      NaN               140.741660   
01004                                      NaN             10313.446515   
01005                                      NaN              1144.429311   
01006                                      NaN                77.033834   

                   Déchets     Energie  Industrie hors-énergie   Résidentiel  \
INSEE commune                                                                  
01001           101.430476    2.354558                6.911213    309.358195   
01002           140.675439    2.354558                6.911213    104.866444   
01004          5314.314445  998.332482             2930.354461  16616.822534   
01005           216.217508   94.182310              276.448534    663.683146   
01006            48.401549         NaN                     NaN     43.714019   

                    Routier     Tertiaire  
INSEE commune                              
01001            793.156501    367.036172  
01002            348.997893    112.934207  
01004          15642.420313  10732.376934  
01005           1756.341319    782.404357  
01006            398.786800     51.681756

In [31]:
df.iloc[0, 1]

np.float64(3711.42599095982)

In [33]:
df2 = df.loc[['01002', '01103'], ['Agriculture', 'Energie']].copy()

Agriculture   Energie
INSEE commune                       
01002           475.330205  2.354558
01103           721.915371  2.354558

In [35]:
df.loc[df['Agriculture'].isna()]

Commune  Agriculture  Autres transports  \
INSEE commune                                                          
01026                 BAGE-LE-CHATEL          NaN                NaN   
10294                        POLIGNY          NaN                NaN   
14022                       ASNELLES          NaN                NaN   
29238                      ROSCANVEL          NaN          39.653211   
31157                        CUGNAUX          NaN                NaN   
...                              ...          ...                ...   
92064                    SAINT-CLOUD          NaN         499.838509   
92071                         SCEAUX          NaN         262.438419   
92073                       SURESNES          NaN         247.336505   
92075                         VANVES          NaN          79.711550   
92078          VILLENEUVE-LA-GARENNE          NaN          51.592570   

               Autres transports international  CO2 biomasse hors-total  \
INSEE commune                                                             
01026                                      NaN               558.461375   
10294                                      NaN               221.930563   
14022                                      NaN               478.369246   
29238                                      NaN               576.892650   
31157                                      NaN             13849.612131   
...                                        ...                      ...   
92064                                 9.285022             32456.239529   
92071                                      NaN              4700.863382   
92073                                 1.104401             39179.191628   
92075                                      NaN              5629.858490   
92078                                      NaN             14028.190978   

                   Déchets      Energie  Industrie hors-énergie   Résidentiel  \
INSEE commune                                                                   
01026           113.067871    11.772789               34.556067    859.949666   
10294             8.860289     2.354558                6.911213     31.011980   
14022            77.626714     9.418231               27.644853    346.521835   
29238           113.861330     2.354558                6.911213    503.841885   
31157          7872.703168  1094.869350             3213.714208  15833.086268   
...                    ...          ...                     ...           ...   
92064           240.467819  8186.797266            24030.288820  29644.673627   
92071           162.889294   372.020123             1091.971709  22441.364597   
92073           397.070535  8857.846222            25999.984625  50004.254857   
92075           232.710793   308.447064              905.368949  21107.409249   
92078           210.373200  2658.295690             7802.759873  17559.313727   

                    Routier     Tertiaire  
INSEE commune                              
01026           2130.101491    409.147233  
10294           2198.295062     32.061830  
14022            379.173561    280.899913  
29238           2034.092145    412.018441  
31157          18094.498491  10362.750974  
...                     ...           ...  
92064          64868.314960  13929.668762  
92071           9691.146620   9435.748691  
92073          23302.575643  24239.062880  
92075           7403.982800  13640.804788  
92078          19680.354360  14447.449205  

[62 rows x 11 columns]

In [37]:
df['Agriculture'] = df['Agriculture'].fillna(df['Agriculture'].mean())
df.loc['01026']

Commune                            BAGE-LE-CHATEL
Agriculture                            2459.97576
Autres transports                             NaN
Autres transports international               NaN
CO2 biomasse hors-total                558.461375
Déchets                                113.067871
Energie                                 11.772789
Industrie hors-énergie                  34.556067
Résidentiel                            859.949666
Routier                               2130.101491
Tertiaire                              409.147233
Name: 01026, dtype: object

In [ ]:
df.dropna()